db:
  scripts:
    - conf/init.sql
app:
  mode: prod
  resps:
    - name: system_fault
      errcode: 1000
    - name: user_not_exist
      errcode: 1001
    - name: password_error
      errcode: 1002
logs:
  - level: debug
    format: text
    outType: console