db:
  scripts:
    - conf/init.sql
app:
  mode: prod
  resps:
    - name: fault
      errcode: 1000
      errmsg: 系统故障
    - name: loginFailed
      errcode: 1001
      errmsg: 登陆失败
logs:
  - level: debug
    format: text
    outType: console