name: publish docker-registry

on:
  push:
    paths-ignore:
      - docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish to docker-registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fortune
          username: ${{secrets.DOCKER_REGISTRY_USERNAME}}
          password: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
          tags: latest
          registry: www.takujo.cn:5000
